/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
<<<<<<< HEAD
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as TestCreateRouteImport } from './routes/test/create'
=======
import { Route as ActivityIndexRouteImport } from './routes/activity/index'
>>>>>>> b7e3721531f2964bb05576a7b0e63c0c913bbb01
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCreateRoute = TestCreateRouteImport.update({
  id: '/test/create',
  path: '/test/create',
=======
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
>>>>>>> b7e3721531f2964bb05576a7b0e63c0c913bbb01
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/test/create': typeof TestCreateRoute
  '/test/': typeof TestIndexRoute
=======
  '/activity/': typeof ActivityIndexRoute
>>>>>>> b7e3721531f2964bb05576a7b0e63c0c913bbb01
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/test/create': typeof TestCreateRoute
  '/test': typeof TestIndexRoute
=======
  '/activity': typeof ActivityIndexRoute
>>>>>>> b7e3721531f2964bb05576a7b0e63c0c913bbb01
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/test/create': typeof TestCreateRoute
  '/test/': typeof TestIndexRoute
=======
  '/activity/': typeof ActivityIndexRoute
>>>>>>> b7e3721531f2964bb05576a7b0e63c0c913bbb01
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
<<<<<<< HEAD
  fullPaths:
    | '/'
    | '/test/create'
    | '/test/'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test/create'
    | '/test'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/test/create'
    | '/test/'
=======
  fullPaths: '/' | '/activity/' | '/demo/form/address' | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activity' | '/demo/form/address' | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/activity/'
>>>>>>> b7e3721531f2964bb05576a7b0e63c0c913bbb01
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
<<<<<<< HEAD
  TestCreateRoute: typeof TestCreateRoute
  TestIndexRoute: typeof TestIndexRoute
=======
  ActivityIndexRoute: typeof ActivityIndexRoute
>>>>>>> b7e3721531f2964bb05576a7b0e63c0c913bbb01
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/create': {
      id: '/test/create'
      path: '/test/create'
      fullPath: '/test/create'
      preLoaderRoute: typeof TestCreateRouteImport
=======
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof ActivityIndexRouteImport
>>>>>>> b7e3721531f2964bb05576a7b0e63c0c913bbb01
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
<<<<<<< HEAD
  TestCreateRoute: TestCreateRoute,
  TestIndexRoute: TestIndexRoute,
=======
  ActivityIndexRoute: ActivityIndexRoute,
>>>>>>> b7e3721531f2964bb05576a7b0e63c0c913bbb01
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
